#!/bin/bash
# Runs before Write or Edit tool use — blocks writes to sensitive files.
# Exit 0 = allow, Exit 2 = block

FILE="$CLAUDE_TOOL_INPUT_FILE_PATH"

if [ -z "$FILE" ]; then
  exit 0
fi

# Block writes to environment files (only .env.example is allowed)
if echo "$FILE" | grep -qE '\.env$|\.env\.local$|\.env\.production$'; then
  echo "BLOCKED: Writing to '$FILE' is not allowed. Use .env.example for committed env templates."
  exit 2
fi

# Block writes to Prisma migrations (must be generated by CLI, not manually edited)
if echo "$FILE" | grep -qE 'prisma/migrations/.*\.sql$'; then
  echo "BLOCKED: Do not manually edit Prisma migration files. Use 'npm run db:migrate' instead."
  exit 2
fi

# Block writes to package-lock.json (must be managed by npm)
if echo "$FILE" | grep -qE 'package-lock\.json$'; then
  echo "BLOCKED: Do not manually edit package-lock.json. Run 'npm install' instead."
  exit 2
fi

exit 0
