/**
 * Hotjar loader — session recordings, heatmaps, and whatever else is enabled
 * in the Hotjar dashboard for the configured site.
 *
 * Two entry points:
 *   initHotjar()             — inject the Hotjar snippet (safe to call twice)
 *   identifyHotjarUser(user) — attach the signed-in user to the recording
 *
 * The Site ID is never hardcoded here. It arrives at runtime on
 * window.APP_CONFIG, which /config.js (generated by server.js) fills in from
 * the HOTJAR_SITE_ID environment variable. Blank or absent means no snippet is
 * injected and no request to static.hotjar.com is made at all — that is the
 * committed default, so local dev never records into the same Hotjar site as
 * real users.
 *
 * Loaded as a classic script by both index.html and login.html, so the login
 * screen is covered too.
 */
(function () {
  'use strict';

  // The idempotency guard. Two snippets on one page means two recordings per
  // page view, which would inflate the exact counts Hotjar exists to measure,
  // so the DOM is the source of truth for "already loaded" — an element id
  // survives this module being evaluated twice, which a module-local flag
  // would not.
  var HOTJAR_SCRIPT_ID = 'hotjar-loader';

  // Snippet version Hotjar's own loader pins. Used in both _hjSettings.hjsv
  // and the ?sv= query param, exactly as the vendor snippet does.
  var HOTJAR_SNIPPET_VERSION = 6;

  // Hotjar's opt-out attribute: the element's text and its descendants' text
  // are replaced with asterisks in recordings and heatmaps. Layout, clicks and
  // scroll data survive, so suppressed regions still produce usable analytics.
  var SUPPRESS_ATTR = 'data-hj-suppress';

  var overlayObserver = null;

  /**
   * Suppress dialogs, menus, pickers and lightboxes that app.js appends
   * straight to <body> (~20 call sites: confirm dialogs echoing a user's name
   * and email, the worklog editor, the attachment lightbox, assignee pickers).
   *
   * Static markup carries SUPPRESS_ATTR in index.html, but body-appended nodes
   * are created after that markup is parsed, so no static attribute can reach
   * them. This observer is the one place that covers them — including overlays
   * added by code written later, which a list of per-call-site attributes
   * would silently miss.
   *
   * Default-deny on purpose: every new direct child of <body> is suppressed
   * rather than matching a list of known overlay classes. Over-masking a menu
   * costs nothing (its labels are static UI we already know), while missing one
   * dialog leaks a real person's data. Only runs when Hotjar actually loaded.
   */
  function observeBodyOverlays() {
    if (overlayObserver) return;
    if (typeof MutationObserver !== 'function') return;

    if (!document.body) {
      // Script parsed before <body> existed — retry once the DOM is ready.
      document.addEventListener('DOMContentLoaded', observeBodyOverlays, { once: true });
      return;
    }

    overlayObserver = new MutationObserver(function (records) {
      for (var i = 0; i < records.length; i++) {
        var added = records[i].addedNodes || [];
        for (var j = 0; j < added.length; j++) {
          var node = added[j];
          if (!node || node.nodeType !== 1) continue; // elements only
          if (node.hasAttribute(SUPPRESS_ATTR)) continue;
          node.setAttribute(SUPPRESS_ATTR, '');
        }
      }
    });
    // childList without subtree: direct children of <body> only, so this never
    // walks the app's own re-renders.
    overlayObserver.observe(document.body, { childList: true });
  }

  function configuredSiteId() {
    var cfg = (typeof window !== 'undefined' && window.APP_CONFIG) || {};
    var raw = cfg.hotjarSiteId;
    if (raw === undefined || raw === null) return '';
    return String(raw).trim();
  }

  /**
   * Inject the Hotjar snippet. Idempotent — calling it a second time is a
   * no-op that returns true.
   *
   * @returns {boolean} true if Hotjar is loaded (or was already), false if it
   *   is switched off or the configured Site ID is unusable.
   */
  function initHotjar() {
    if (typeof window === 'undefined' || typeof document === 'undefined') return false;

    var raw = configuredSiteId();

    // Not configured. This is the intended default, not a problem — stay
    // silent and request nothing.
    if (!raw) return false;

    // A typo in HOTJAR_SITE_ID would otherwise request hotjar-NaN.js and fail
    // in a way that looks identical to Hotjar being switched off. Say so
    // out loud instead of loading a broken snippet.
    if (!/^[0-9]+$/.test(raw) || Number(raw) <= 0) {
      console.warn('[hotjar] Ignoring invalid HOTJAR_SITE_ID ' + JSON.stringify(raw) +
        ' — expected a positive integer. Hotjar not loaded.');
      return false;
    }

    if (document.getElementById(HOTJAR_SCRIPT_ID)) { observeBodyOverlays(); return true; }

    // hjid must be a Number, matching Hotjar's own snippet: it is
    // string-concatenated into the script URL and read back by the vendor
    // code, which expects a numeric id.
    window.hj = window.hj || function () { (window.hj.q = window.hj.q || []).push(arguments); };
    window._hjSettings = { hjid: Number(raw), hjsv: HOTJAR_SNIPPET_VERSION };

    var script = document.createElement('script');
    script.id = HOTJAR_SCRIPT_ID;
    script.async = true;
    script.src = 'https://static.hotjar.com/c/hotjar-' + window._hjSettings.hjid +
      '.js?sv=' + HOTJAR_SNIPPET_VERSION;

    var head = document.getElementsByTagName('head')[0] || document.documentElement;
    head.appendChild(script);

    observeBodyOverlays();
    return true;
  }

  /**
   * Tell Hotjar who is using the app, so recordings and heatmaps can be
   * filtered by person and role.
   *
   * The user id is the Hotjar User ID (stable across email changes and
   * casing), and the email attribute is lowercased so one person is one
   * Hotjar user rather than two.
   *
   * Safe to call when Hotjar is switched off — it just returns false.
   *
   * @param {{id?: string, email?: string, role?: string}} user
   * @returns {boolean} true if the identify call was handed to Hotjar.
   */
  function identifyHotjarUser(user) {
    if (typeof window === 'undefined') return false;
    if (typeof window.hj !== 'function') return false;
    if (!user) return false;

    var email = user.email ? String(user.email).trim().toLowerCase() : '';
    var userId = user.id ? String(user.id) : email;
    if (!userId) return false;

    var attrs = {};
    if (email) attrs.email = email;
    if (user.role) attrs.role = String(user.role);

    try {
      window.hj('identify', userId, attrs);
    } catch (e) {
      console.warn('[hotjar] identify failed: ' + e.message);
      return false;
    }
    return true;
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { initHotjar: initHotjar, identifyHotjarUser: identifyHotjarUser };
    // Exported for the tests in scripts/test-hotjar.js, so the guard's element
    // id and the suppression attribute are asserted from one place rather than
    // duplicated as literals.
    module.exports.HOTJAR_SCRIPT_ID = HOTJAR_SCRIPT_ID;
    module.exports.SUPPRESS_ATTR = SUPPRESS_ATTR;
  }
  if (typeof window !== 'undefined') {
    window.initHotjar = initHotjar;
    window.identifyHotjarUser = identifyHotjarUser;
  }
})();
